/** Les libellés du shell, rendus dans la langue du projet à sa création. */
export const TEXTES = {
  espace: 'Administration',
  connexion: 'Connexion',
  connexion_sous_titre:
    'Cet espace est celui du compte qui administre le service. Les identifiants sont ceux de la table des comptes que ce projet porte.',
  adresse: 'Adresse',
  mot_de_passe: 'Mot de passe',
  entrer: 'Entrer',
  entree_en_cours: 'Vérification…',
  refuse: 'Adresse ou mot de passe refusé.',
  injoignable: "Le service n'a pas répondu.",
  oubli: 'Mot de passe oublié',
  oubli_titre: 'Réinitialiser le mot de passe',
  oubli_detail:
    "Un lien de réinitialisation part à cette adresse si un compte l'utilise. La réponse est la même dans les deux cas : elle ne dit pas qui est inscrit.",
  envoyer: 'Envoyer',
  envoi_en_cours: 'Envoi…',
  envoye: 'Demande enregistrée. Regardez la boîte de réception de cette adresse.',
  annuler: 'Annuler',
  menu: 'Afficher le rail',
  tableau: 'Tableau de bord',
  sessions: 'Sessions',
  profil: 'Profil',
  chargement: 'Chargement…',
  sondes: 'Sondes',
  sonde: 'Dépendance',
  verdict: 'Verdict',
  verdict_ensemble: "Verdict d'ensemble : ",
  aucune_sonde: "Le service a répondu sans nommer une seule dépendance.",
  sante_injoignable: "La sonde n'a pas répondu.",
  sante_illisible: 'La sonde a répondu autre chose que ce que cet écran sait lire.',
  contrat: 'Contrat',
  version: 'Version',
  routes: 'Routes montées',
  routes_source: 'lues dans le document OpenAPI que le service publie',
  document_injoignable: "Le document OpenAPI n'est pas servi.",
  inconnu: 'inconnue',
  sessions_titre: 'Sessions ouvertes',
  sessions_detail:
    "Une ligne par jeton de rafraîchissement encore vivant sur ce compte. Le service ne dit pas laquelle est la vôtre : il ne voit jamais la ligne qui a émis le jeton que vous portez.",
  identifiant: 'Identifiant',
  ouverte_le: 'Ouverte le',
  expire_le: 'Expire le',
  revoquer: 'Révoquer',
  revocation_en_cours: 'Révocation…',
  session_revoquee: 'Session révoquée.',
  revocation_refusee: "La session n'a pas été révoquée.",
  aucune_session: 'Aucune session ouverte. Se connecter en ouvre une.',
  sessions_illisibles: "La liste des sessions n'est pas venue.",
  revoquer_tout: 'Révoquer toutes les sessions',
  revoquer_tout_titre: 'Révoquer toutes les sessions',
  revoquer_tout_detail:
    'Toutes les sessions de ce compte tombent, celle-ci comprise : vous serez déconnecté et devrez vous reconnecter.',
  compte: 'Compte',
  role: 'Rôle',
  verification: "Preuve de l'adresse",
  adresse_non_verifiee: "Adresse pas encore prouvée",
  inscrit_le: 'Inscrit le',
  profil_illisible: "Le compte n'est pas venu.",
  mot_de_passe_titre: 'Changer le mot de passe',
  mot_de_passe_detail:
    'Toutes les sessions de ce compte tombent et une paire neuve est émise : cet onglet reste ouvert, les autres non.',
  mot_de_passe_courant: 'Mot de passe courant',
  nouveau_mot_de_passe: 'Nouveau mot de passe',
  confirmation: 'Nouveau mot de passe, encore',
  confirmation_differente: 'Les deux saisies diffèrent.',
  changer: 'Changer',
  changement_en_cours: 'Changement…',
  mot_de_passe_change: 'Mot de passe changé. Les autres sessions sont fermées.',
  changement_refuse: "Le mot de passe n'a pas été changé.",
  sortir: 'Se déconnecter',
  deconnecte: 'Session fermée.',
  session_expiree: 'La session a pris fin. Reconnectez-vous pour continuer.',
} as const

