/** Les libellés de la galerie, rendus dans la langue du projet à sa création. */
export const TEXTES = {
  titre: 'Galerie',
  sous_titre:
    "Les quatorze composants que le socle a déposés dans ce projet, chacun dans ses états principaux. Ils vous appartiennent : ils sont sous `src/components/ui`, et rien n'en tient la forme hors de ce dépôt.",
  theme:
    "Aucun ne nomme une couleur. Tout ce qu'ils affichent vient du bloc de thème de `src/assets/main.css` ; le réécrire change l'identité sans toucher à une ligne de composant.",
  bouton: 'Bouton',
  enregistrer: 'Enregistrer',
  annuler: 'Annuler',
  exporter: 'Exporter',
  ignorer: 'Ignorer',
  en_savoir_plus: 'En savoir plus',
  revoquer: 'Révoquer',
  petit: 'Petit',
  grand: 'Grand',
  ajouter: 'Ajouter',
  indisponible: 'Indisponible',
  champ: 'Champ',
  verrouille: 'verrouillé',
  etiquette: 'Étiquette',
  hote: 'Hôte',
  carte: 'Carte',
  sonde: 'Sonde de santé',
  releve: 'Relevé de la dernière minute',
  base_jointe: 'Base de données jointe, migrations à jour.',
  interroger: 'Interroger',
  badge: 'Badge',
  ouverte: 'ouverte',
  brouillon: 'brouillon',
  fermee: 'fermée',
  revoquee: 'révoquée',
  separateur: 'Séparateur',
  au_dessus: 'Au-dessus du filet',
  lecture: 'lecture',
  ecriture: 'écriture',
  purge: 'purge',
  table: 'Table',
  routes_montees: 'Les routes que le projet monte',
  route: 'Route',
  methode: 'Méthode',
  etat: 'État',
  total: 'Total',
  session: 'Session',
  aucune_session: 'Aucune session ouverte',
  dialogue: 'Boîte de dialogue',
  revoquer_session: 'Révoquer la session',
  revoquer_detail: 'Le porteur de ce jeton sera déconnecté à sa prochaine requête.',
  menu: 'Menu déroulant',
  colonnes: 'Colonnes',
  affichage: 'Affichage',
  rafraichir: 'Rafraîchir',
  panneau: 'Panneau latéral',
  ouvrir_detail: 'Ouvrir le détail',
  bord_droit: 'par la droite',
  bord_gauche: 'par la gauche',
  session_une: 'Session 1',
  session_detail: 'Ouverte depuis douze minutes, depuis 127.0.0.1.',
  liste: 'Liste de sélection',
  trier_par: 'Trier par',
  ordre: 'Ordre',
  plus_recentes: "Plus récentes d'abord",
  plus_anciennes: 'Plus anciennes d\'abord',
  par_nom: 'Par nom',
  case_a_cocher: 'Case à cocher',
  session_active: 'Session active',
  session_courante: 'Session courante',
  session_verrouillee: 'Verrouillée par la politique',
  squelette: 'Squelette de chargement',
  notifications: 'Notifications',
  succes: 'Succès',
  erreur: 'Erreur',
  avec_description: 'Avec description',
  session_revoquee: 'Session révoquée',
  pas_de_reponse: "Le service n'a pas répondu",
  migration_appliquee: 'Migration appliquée',
  retour: "Retour à l'accueil",
}

